sudo: required
services:
  - docker

before_install:
  - docker build -t dmcgeown-deveire/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmcgeown-deveire/react-test npm test

after_success:
  - docker build dmcgeown/multi-client -f ./client
  - docker build dmcgeown/multi-nginx -f ./nginx
  - docker build dmcgeown/multi-server -f ./server
  - docker build dmcgeown/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dmcgeown/multi-client
  - docker push dmcgeown/multi-nginx
  - docker push dmcgeown/multi-server
  - docker push dmcgeown/multi-worker